from fuzzywuzzy import process

# Example lists
full_names = [
  "VAN DER POEL Mathieu",
  "PHILIPSEN Jasper",
  "MEURISSE Xandro",
  "DILLIER Silvan",
  "GROVES Kaden",
  "VERMEERSCH Gianni",
  "HERMANS Quinten",
  "RIESEBEEK Oscar",
  "GOGL Michael",
  "RICKAERT Jonas",
  "JANSSENS Jimmy",
  "PLANCKAERT Edward",
  "KIELICH Timo",
  "VAN TRICHT Stan",
  "BAYER Tobias",
  "GHYS Robbe",
  "PLOWRIGHT Jensen",
  "DEHAIRS Simon",
  "VAN DEN BOSSCHE Fabio",
  "UHLIG Henri",
  "HOLLMANN Juri",
  "BOVEN Lars",
  "PRICE-PEJTERSEN Johan",
  "VERGALLITO Luca",
  "GLIVAR Gal",
  "DEL GROSSO Tibor",
  "DEBRUYNE Ramses",
  "VERSTRYNGE Emiel",
  "GAZE Samuel",
  "DÉMARE Arnaud",
  "SÉNÉCHAL Florian",
  "VENTURINI Clément",
  "CAPIOT Amaury",
  "DELAPLACE Anthony",
  "MOZZATO Luca",
  "VAUQUELIN Kévin",
  "RODRÍGUEZ Cristián",
  "BIERMANS Jenthe",
  "GESBERT Élie",
  "SCOTSON Miles",
  "GUERNALEC Thibault",
  "COSTIOU Ewen",
  "GARCÍA PIERNA Raúl",
  "GUGLIELMI Simon",
  "HUYS Laurens",
  "RIES Michel",
  "VERRE Alessandro",
  "LE BERRE Mathis",
  "GRONDIN Donavan",
  "SVESTAD-BÅRDSENG Embret",
  "THIERRY Pierre",
  "TJØTTA Martin",
  "EPIS Giosuè",
  "ROULAND Louis",
  "LOZOUET Léandre",
  "GUERNALEC Victor",
  "BILBAO Pello",
  "CARUSO Damiano",
  "MOHORIČ Matej",
  "PASQUALON Andrea",
  "HAIG Jack",
  "BAUHAUS Phil",
  "ARNDT Nikias",
  "BUITRAGO Santiago",
  "MARTINEZ Lenny",
  "TIBERI Antonio",
  "WRIGHT Fred",
  "GRADEK Kamil",
  "TRÆEN Torstein",
  "ZAMBANINI Edoardo",
  "GOVEKAR Matevž",
  "STANNARD Robert",
  "PAASSCHENS Mathijs",
  "KEPPLINGER Rainer",
  "MIHOLJEVIĆ Fran",
  "EULÁLIO Afonso",
  "BURATTI Nicolò",
  "TU Sergio",
  "BRUTTOMESSO Alberto",
  "SKERL Daniel",
  "PICKERING Finlay",
  "STOCKWELL Oliver",
  "ERMAKOV Roman",
  "VAN DER MEULEN Max",
  "VAN MECHELEN Vlad",
  "ERŽEN Žak",
  "KUDUS Merhawi",
  "SAINBAYAR Jambaljamts",
  "DÍAZ José Manuel",
  "FAGÚNDEZ Eric Antonio",
  "BOUGLAS Georgios",
  "JACKSON George",
  "OKAMIKA Ander",
  "APARICIO Mario",
  "CHUMIL Sergio Geovani",
  "ANGULO Antonio",
  "BURNETT Josh",
  "FUENTES Ángel",
  "ALLENO Clément",
  "MARTIN David",
  "GARCÍA PIERNA Carlos",
  "ÁLVAREZ Rodrigo",
  "DE LA CALLE Hugo",
  "FERNÁNDEZ Sinuhé",
  "DELGADO David",
  "KMÍNEK Vojtěch",
  "FAURA José Luis",
  "CAVIA Daniel",
  "KOYAMA Tomoya",
  "PRADES Eduard",
  "BARCELÓ Fernando",
  "OTRUBA Jakub",
  "BERWICK Sebastian",
  "BOU Joan",
  "SILVA Guillermo Thomas",
  "MOLENAAR Alex",
  "LEITÃO Iúri",
  "GONZÁLEZ Abner",
  "NICOLAU Joel",
  "STITES Tyler",
  "BABOR Daniel",
  "BALDERSTONE Abel",
  "SORARRAIN Gorka",
  "GUARDEÑO Jaume",
  "PEÑUELA Francisco Joel",
  "LÓPEZ Joseba",
  "DARDER Sergi",
  "JOHNSTON Calum",
  "FERNÁNDEZ Samuel",
  "CASTELLON Jan",
  "ARRIOLA-BENGOA Julen",
  "DIAZ Alex",
  "IBAÑEZ Javier",
  "BENNETT Sam",
  "NAESEN Oliver",
  "COSNEFROY Benoît",
  "VENDRAME Andrea",
  "PARET-PEINTRE Aurélien",
  "GODON Dorian",
  "DE BONDT Dries",
  "GALL Felix",
  "BISSEGGER Stefan",
  "DEWULF Stan",
  "LAFAY Victor",
  "PETERS Nans",
  "BOUCHARD Geoffrey",
  "ARMIRAIL Bruno",
  "BERTHET Clément",
  "LAPEIRA Paul",
  "PRODHOMME Nicolas",
  "GAUTHERAT Pierre",
  "SCOTSON Callum",
  "TRONCHON Bastien",
  "STAUNE-MITTET Johannes",
  "GUDMESTAD Tord",
  "DE PESTEL Sander",
  "LABROSSE Jordan",
  "ISIDORE Noa",
  "PEDERSEN Rasmus Søjberg",
  "POLLEFLIET Gianluca",
  "BISIAUX Léo",
  "SEIXAS Paul",
  "CHAMBERLAIN Oscar",
  "COSTA Rui",
  "CARAPAZ Richard",
  "CHAVES Esteban",
  "VALGREN Michael",
  "POWLESS Neilson",
  "ASGREEN Kasper",
  "CARTHY Hugh",
  "ALBANESE Vincenzo",
  "HONORÉ Mikkel Frølich",
  "VAN DEN BERG Marijn",
  "HEALY Ben",
  "DOULL Owain",
  "BATTISTELLA Samuele",
  "CEPEDA Jefferson Alexander",
  "BAUDIN Alex",
  "SHAW James",
  "MIHKELS Madis",
  "STEINHAUSER Georg",
  "RYAN Archie",
  "SWEENY Harry",
  "QUINN Sean",
  "NERURKAR Lukas",
  "RAFFERTY Darren",
  "WALKER Max",
  "ROOTKIN-GRAY Jack",
  "VAN DER LEE Jardi Christiaan",
  "MACKELLAR Alastair",
  "TODOME Yuhi",
  "BELOKI Markel",
  "ABERASTURI Jon",
  "DE LA PARTE Víctor",
  "BIZKARRA Mikel",
  "MARTÍN Gotzon",
  "DINA Márton",
  "DEKKER David",
  "JUARISTI Txomin",
  "LÓPEZ Jordi",
  "BERASATEGI Xabier",
  "AGIRRE Jon",
  "MURGUIALDAY Jokin",
  "HENNEQUIN Paul",
  "LÓPEZ DE ABETXUKO Andoni",
  "ISASA Xabier",
  "MINTEGI Iker",
  "VAN DER TUUK Danny",
  "SUTTON Louis",
  "BONILLO Iker",
  "GANZABAL Ander",
  "ZUBELDIA Unai",
  "ALUSTIZA Nicolás",
  "VAN POUCKE Aaron",
  "HESTERS Jules",
  "DE VYLDER Lindsay",
  "VANHOOF Ward",
  "VAN HEMELEN Vincent",
  "COLMAN Alex",
  "MARIS Elias",
  "VANDENSTORME Dylan",
  "VANDEVELDE Yentl",
  "CLYNHENS Toon",
  "VERCOUILLIE Victor",
  "DEJAEGHER Jasper",
  "GEENS Jonas",
  "DEWEIRDT Siebe",
  "DENS Tuur",
  "VANDENBRANDEN Noah",
  "CRABBE Tom",
  "LANHOVE Milan",
  "DEMAN Brem",
  "GERITS Vince",
  "KÜNG Stefan",
  "MARTIN Guillaume",
  "GAUDU David",
  "MADOUAS Valentin",
  "MOLARD Rudy",
  "CAVAGNA Rémi",
  "PACHER Quentin",
  "BYSTRØM Sven Erik",
  "GRÉGOIRE Romain",
  "PENHOËT Paul",
  "LE GAC Olivier",
  "ROCHAS Rémy",
  "GENIETS Kevin",
  "RUSSO Clément",
  "ASKEY Lewis",
  "BARTHE Cyril",
  "WALLS Matthew",
  "JACOBS Johan",
  "DONNENWIRTH Tom",
  "VAN DEN BERG Lars",
  "PALENI Enzo",
  "GERMANI Lorenzo",
  "GRUEL Thibaud",
  "BRAZ AFONSO Clément",
  "DAVY Clément",
  "ROLLAND Brieuc",
  "LE HUITOUZE Eddy",
  "THOMAS Geraint",
  "KWIATKOWSKI Michał",
  "EWAN Caleb",
  "BERNAL Egan",
  "JUNGELS Bob",
  "GANNA Filippo",
  "SWIFT Ben",
  "CASTROVIEJO Jonathan",
  "RODRÍGUEZ Carlos",
  "ARENSMAN Thymen",
  "DE PLUS Laurens",
  "FRAILE Omar",
  "SHEFFIELD Magnus",
  "HAMILTON Lucas",
  "FOSS Tobias",
  "PUCCIO Salvatore",
  "SWIFT Connor",
  "RODRÍGUEZ Óscar",
  "LAURANCE Axel",
  "TARLING Joshua",
  "TURNER Ben",
  "WATSON Samuel",
  "RIVERA Brandon Smith",
  "LANGELLOTTI Victor",
  "HEIDUK Kim",
  "AUGUST Andrew",
  "LEONARD Michael",
  "SHMIDT Artem",
  "MEINTJES Louis",
  "GIRMAY Biniam",
  "ROTA Lorenzo",
  "PETIT Adrien",
  "SMITH Dion",
  "THIJSSEN Gerben",
  "VAN DER HOORN Taco",
  "ZIMMERMANN Georg",
  "KAMP Alexander",
  "PETILLI Simone",
  "MARIT Arne",
  "VAN HOECKE Gijs",
  "PAGE Hugo",
  "GOOSSENS Kobe",
  "RUTSCH Jonas",
  "REX Laurenz",
  "BARRÉ Louis",
  "BONNEU Kamiel",
  "BUSATTO Francesco",
  "BRAET Vito",
  "COLLEONI Kevin",
  "VAN BOVEN Luca",
  "PAQUOT Tom",
  "VAN SINTMAARTENSDIJK Roel",
  "ARTZ Huub",
  "DE POOTER Dries",
  "FAURE PROST Alexy",
  "KUYPERS Gerben",
  "FROOME Chris",
  "FUGLSANG Jakob",
  "LUTSENKO Alexey",
  "WOODS Michael",
  "ACKERMANN Pascal",
  "BENNETT George",
  "CLARKE Simon",
  "VAN ASBROECK Tom",
  "HOFSTETTER Hugo",
  "HIRT Jan",
  "HOULE Hugo",
  "STRONG Corbin",
  "BOIVIN Guillaume",
  "NEILANDS Krists",
  "WILLIAMS Stephen",
  "SCHULTZ Nick",
  "GEE Derek",
  "LOUVEL Matis",
  "STEWART Jake",
  "VERNON Ethan",
  "EINHORN Itamar",
  "SCHWARZMANN Michael",
  "CÔTÉ Pier-André",
  "BLACKMORE Joseph",
  "SHEEHAN Riley",
  "RICCITELLO Matthew",
  "FRIGO Marco",
  "KOGUT Oded",
  "PICKRELL Riley",
  "RAISBERG Nadav",
  "MATTHEWS Michael",
  "GROENEWEGEN Dylan",
  "O'CONNOR Ben",
  "MEZGEC Luka",
  "DURBRIDGE Luke",
  "WALSCHEID Max",
  "DE MARCHI Alessandro",
  "DUNBAR Eddie",
  "JUUL-JENSEN Christopher",
  "SCHMID Mauro",
  "ZANA Filippo",
  "HARPER Chris",
  "BOUWMAN Koen",
  "HEPBURN Michael",
  "SÜTTERLIN Jasha",
  "PLAPP Luke",
  "REINDERS Elmar",
  "ENGELHARDT Felix",
  "DOUBLE Paul",
  "FOLDAGER Anders",
  "DE PRETTO Davide",
  "KRIJNSEN Jelte",
  "GAMPER Patrick",
  "O'BRIEN Kelland",
  "BERHE Welay Hagos",
  "STEWART Campbell",
  "DONALDSON Robert",
  "HELLEMOSE Asbjørn",
  "HATHERLY Alan",
  "SOSA Iván Ramiro",
  "BERRADE Urko",
  "GALVÁN Francisco",
  "PARRA José Félix",
  "MIQUEL Pau",
  "SOTO Antonio Jesús",
  "IRIBAR Unai",
  "RUIZ Ibon",
  "FERNÁNDEZ Miguel Ángel",
  "GUTIÉRREZ Jorge",
  "ELOSEGUI Iñigo",
  "WENZEL Mats",
  "COBO Iván",
  "BRUSTENGA Marc",
  "ETXEBERRIA Haimar",
  "URIARTE Diego",
  "RETEGI Mikel",
  "AZNAR Hugo",
  "AZANZA Ibai",
  "AZNAR Unai",
  "CARRASCOSA Pablo",
  "GIMENO Nil",
  "MOLLEMA Bauke",
  "PEDERSEN Mads",
  "STUYVEN Jasper",
  "KONRAD Patrick",
  "THEUNS Edward",
  "CICCONE Giulio",
  "SKUJIŅŠ Toms",
  "KRAGH ANDERSEN Søren",
  "SKJELMOSE Mattias",
  "GEOGHEGAN HART Tao",
  "CONSONNI Simone",
  "OOMEN Sam",
  "KÄMNA Lennard",
  "VERONA Carlos",
  "MILAN Jonathan",
  "GIBBONS Ryan",
  "BAGIOLI Andrea",
  "GHEBREIGZABHIER Amanuel",
  "KIRSCH Alex",
  "DECLERCQ Tim",
  "VACEK Mathias",
  "NYS Thibau",
  "BERNARD Julien",
  "SIMMONS Quinn",
  "LÓPEZ Juan Pedro",
  "MOSCA Jacopo",
  "HOOLE Daan",
  "TEUTENBERG Tim Torn",
  "VERGAERDE Otto",
  "WITHEN PHILIPSEN Albert",
  "DE LIE Arnaud",
  "DE BUYST Jasper",
  "SEPÚLVEDA Eduardo",
  "MENTEN Milan",
  "VAN EETVELT Lennert",
  "TAMINIAUX Lionel",
  "VAN MOER Brent",
  "BERCKMOES Jenno",
  "SEGAERT Alec",
  "BEULLENS Cedric",
  "GREGAARD Jonas",
  "LIVYNS Arjen",
  "VAN DE PAAR Jarne",
  "CURRIE Logan",
  "THOMPSON Reuben",
  "SLOCK Liam",
  "VANDENABEELE Henri",
  "GRIGNARD Sébastien",
  "DRIZNERS Jarrad",
  "DE SCHUYTENEER Steffen",
  "CRAPS Lars",
  "VAN DE WYNKELE Lorenz",
  "ORINS Robin",
  "VEISTROFFER Baptiste",
  "GIDDINGS Joshua",
  "QUINTANA Nairo",
  "MAS Enric",
  "GAVIRIA Fernando",
  "FORMOLO Davide",
  "OLIVEIRA Nelson",
  "CIMOLAI Davide",
  "GUERREIRO Ruben",
  "GARCÍA CORTINA Iván",
  "MÜHLBERGER Gregor",
  "RUBIO Einer",
  "AULAR Orluis",
  "TESFATSION Natnael",
  "SERRANO Gonzalo",
  "PEDRERO Antonio",
  "CEPEDA Jefferson Alveiro",
  "ROMO Javier",
  "BARTA Will",
  "SÁNCHEZ Pelayo",
  "CANAL Carlos",
  "CASTRILLO Pablo",
  "NORSGAARD Mathias",
  "ARCAS Jorge",
  "TORRES Albert",
  "BARRENETXEA Jon",
  "ROMEO Iván",
  "MILESI Lorenzo",
  "HESSMANN Michel",
  "PESCADOR Diego",
  "MORO Manlio",
  "PERON Andrea",
  "KOPECKÝ Matyáš",
  "LOZANO David",
  "BRAND Sam",
  "POLI Umberto",
  "RIDOLFO Filippo",
  "BEADLE Hamish",
  "MCDONALD Bailey",
  "WATTELLE Célestin",
  "IRVINE Declan",
  "PERRACCHIONE Alessandro",
  "COLLADON Jacopo",
  "ARMITT Hamish",
  "DAUGE Lucas",
  "DE GRAEVE Quinten",
  "MULLER Anton",
  "PERCRULE Doriand",
  "PHIPPEN Logan",
  "POLGA Antonio",
  "SMITH Nathan",
  "BARDET Romain",
  "DEGENKOLB John",
  "BARGUIL Warren",
  "JAKOBSEN Fabio",
  "ONLEY Oscar",
  "ROOSEN Timo",
  "HAMILTON Chris",
  "VERMAERKE Kevin",
  "WELTEN Bram",
  "POOLE Max",
  "EEKHOFF Nils",
  "COMBAUD Romain",
  "ANDRESEN Tobias Lund",
  "EDMONDSON Alex",
  "VAN UDEN Casper",
  "BITTNER Pavel",
  "VAN DEN BROEK Frank",
  "VAN DEN BERG Julius",
  "LEEMREIZE Gijs",
  "DINHAM Matthew",
  "FLYNN Sean",
  "MÄRKL Niklas",
  "LEIJNSE Enzo",
  "NABERMAN Tim",
  "EDDY Patrick",
  "MARTINEZ Guillermo Juan",
  "KOERDT Bjoern",
  "DHONDT Robbe",
  "LONARDI Giovanni",
  "MAESTRI Mirco",
  "PIGANZOLI Davide",
  "TONELLI Alessandro",
  "BAIS Mattia",
  "PEÑALVER Manuel",
  "BAIS Davide",
  "ZOCCARATO Samuele",
  "DE CASSAN Davide",
  "TERCERO Fernando",
  "SEVILLA Diego Pablo",
  "MARTÍN Alex",
  "PIETROBON Andrea",
  "SERRANO Javier",
  "GÓMEZ Germán Darío",
  "CRESCIOLI Ludovico",
  "MUÑOZ Francisco",
  "BUTTIGIEG Aidan",
  "GARCÍA Pablo",
  "RACCAGNI Gabriele",
  "NIZZOLO Giacomo",
  "BRAMBILLA Gianluca",
  "PIDCOCK Thomas",
  "DE LA CRUZ David",
  "HOWSON Damien",
  "MOSCHETTI Matteo",
  "LIEPIŅŠ Emīls",
  "VANHOUCKE Harm",
  "STEIMLE Jannik",
  "BADILATTI Matteo",
  "DONOVAN Mark",
  "BAX Sjoerd",
  "TOWNSEND Rory",
  "FRISON Frederik",
  "MAŁECKI Kamil",
  "CHRISTEN Fabio",
  "VADER Milan",
  "ZUKOWSKY Nickolas",
  "CALZONI Walter",
  "PARISINI Nicolò",
  "GONZÁLEZ David",
  "AZPARREN Xabier Mikel",
  "CAMPRUBÍ Marcel",
  "AZPARREN Enekoitz",
  "PIDCOCK Joseph",
  "ROGLIČ Primož",
  "VAN POPPEL Danny",
  "VLASOV Aleksandr",
  "MARTÍNEZ Daniel Felipe",
  "HINDLEY Jai",
  "MOSCON Gianni",
  "TRATNIK Jan",
  "MEEUS Jordi",
  "VAN GILS Maxim",
  "ALEOTTI Giovanni",
  "ADRIÀ Roger",
  "WELSFORD Sam",
  "PITHIE Laurence",
  "DENZ Nico",
  "SOBRERO Matteo",
  "KOCH Jonas",
  "FISHER-BLACK Finn",
  "LAZKANO Oier",
  "MULLEN Ryan",
  "LIPOWITZ Florian",
  "ZWIEHOFF Ben",
  "PELLIZZARI Giulio",
  "VAN DIJKE Mick",
  "WANDAHL Frederik",
  "VAN DIJKE Tim",
  "MACIEJUK Filip",
  "HAJEK Alexander",
  "PALZER Anton",
  "HERZOG Emil",
  "ARASHIRO Yukiya",
  "SBARAGLI Kristian",
  "CONTI Valerio",
  "FORTIN Filippo",
  "RAJOVIĆ Dušan",
  "STEWART Mark",
  "VIVIANI Attilio",
  "BALDACCINI Davide",
  "BALMER Alexandre",
  "QUARTUCCI Lorenzo",
  "TSARENKO Kyrylo",
  "GONZÁLEZ Roberto Carlos",
  "ĐURIĆ Đorđe",
  "IACCHI Alessandro",
  "SAMUDIO Carlos",
  "NENCINI Tommaso",
  "MEO Felix James",
  "ROLANDO Joann",
  "VERRANDO Luca",
  "PIRAS Andrea",
  "TISSIÈRES Arnaud",
  "EVENEPOEL Remco",
  "LANDA Mikel",
  "LAMPAERT Yves",
  "MERLIER Tim",
  "SCHACHMANN Maximilian",
  "HAYTER Ethan",
  "CATTANEO Mattia",
  "SERRY Pieter",
  "VAN WILDER Ilan",
  "VAN GESTEL Dries",
  "VANSEVENANT Mauri",
  "ČERNÝ Josef",
  "KNOX James",
  "VAN LERBERGHE Bert",
  "EENKHOORN Pascal",
  "PEDERSEN Casper",
  "VERVAEKE Louis",
  "PARET-PEINTRE Valentin",
  "LAMPERTI Luke",
  "WARLOP Jordi",
  "MAGNIER Paul",
  "LECERF Junior",
  "GELDERS Gil",
  "GAROFOLI Gianmarco",
  "VANGHELUWE Warre",
  "HUBY Antoine",
  "SVRČEK Martin",
  "REINDERINK Pepijn",
  "RACCAGNI NOVIERO Andrea",
  "BASTIAENS Ayco",
  "DUPONT Timothy",
  "MARCHAND Gianni",
  "TEUGELS Lennert",
  "BLOUWE Louis",
  "GODART Bo",
  "GOEMAN Jonas",
  "DE KEYSER Ewout",
  "SANTY Arne",
  "VERWILT Mauro",
  "CLAEYS Robbe",
  "BAUWENS Siebe",
  "DECOTTIGNIES Jordy",
  "RIGOLE Brian",
  "STEVENS Daan",
  "MUSEEUW Stefano",
  "VANDENBULCKE Alex",
  "LATOUR Pierre",
  "TURGIS Anthony",
  "MANZIN Lorrenzo",
  "BURGAUDEAU Mathieu",
  "CRAS Steff",
  "TESSON Jason",
  "JEANNIÈRE Emilien",
  "SOUPE Geoffrey",
  "DUJARDIN Sandy",
  "DELETTRE Alexandre",
  "JEGAT Jordan",
  "DOUBEY Fabien",
  "GRELLIER Fabien",
  "GACHIGNARD Thomas",
  "LEROUX Samuel",
  "DELBOVE Joris",
  "VERCHER Mattéo",
  "BRUNEL Alexys",
  "RETAILLEAU Valentin",
  "BONNET Thomas",
  "DAUPHIN Florian",
  "JOUSSEAUME Alan",
  "BONIFACE Lucas",
  "VADIC Baptiste",
  "BOULAHOITE Rayan",
  "MARCEROU Nicola",
  "ALAPHILIPPE Julian",
  "TRENTIN Matteo",
  "HIRSCHI Marc",
  "STORER Michael",
  "HALLER Marco",
  "DE KLEIJN Arvid",
  "DAINESE Alberto",
  "WARBASSE Larry",
  "KRIEGER Alexander",
  "LIENHARD Fabian",
  "VOISARD Yannis",
  "ERIKSSON Lucas",
  "MAYRHOFER Marius",
  "THALMANN Roland",
  "BRENNER Marco",
  "PLUIMERS Rick",
  "STORK Florian",
  "ZIJLAARD Maikel",
  "WIRTGEN Luc",
  "SUTER Joel",
  "FROIDEVAUX Robin",
  "KLUCKERS Arthur",
  "ERIKSSON Jacob",
  "KELEMEN Petr",
  "RONDEL Mathys",
  "HEMING Miká",
  "MIKUTIS Aivaras",
  "WILKSCH Hannes",
  "KOLZE CHANGIZI Sebastian",
  "WEISS Fabian",
  "POGAČAR Tadej",
  "YATES Adam",
  "WELLENS Tim",
  "MAJKA Rafał",
  "ALMEIDA João",
  "MCNULTY Brandon",
  "SIVAKOV Pavel",
  "SOLER Marc",
  "GROßSCHARTNER Felix",
  "POLITT Nils",
  "AYUSO Juan",
  "NARVÁEZ Jhonatan",
  "MOLANO Juan Sebastián",
  "BJERG Mikkel",
  "VINE Jay",
  "VERMEERSCH Florian",
  "LAENGEN Vegard Stake",
  "COVI Alessandro",
  "DEL TORO Isaac",
  "OLIVEIRA Rui",
  "HERREGODTS Rune",
  "MORGADO António",
  "BARONCINI Filippo",
  "NOVAK Domen",
  "CHRISTEN Jan",
  "OLIVEIRA Ivo",
  "JOHANSEN Julius",
  "ARRIETA Igor",
  "TORRES Pablo",
  "EIKING Odd Christian",
  "CARBONI Giovanni",
  "ŤOUPALÍK Adam",
  "BUDDING Martijn",
  "KUBIŠ Lukáš",
  "STOKBRO Andreas",
  "DE VRIES Hartthijs",
  "BLOEM Joren",
  "LOOCKX Lander",
  "BOMBOI Davide",
  "KOPECKÝ Tomáš",
  "CHRISTOPHERSEN Cedrik Bakke",
  "HUENS Axel",
  "INKELAAR Kevin",
  "JOHANNINK Jelle",
  "MAIRE Adrien",
  "KYFFIN Zeb",
  "STOCKMAN Abram",
  "MOURIS Wessel",
  "MERIS Sergio",
  "NIELSEN Sebastian",
  "GELEIJN Owen",
  "VERSCHUREN Killian",
  "PAIGE Charles",
  "HUYET Baptiste",
  "KRISTOFF Alexander",
  "CORT Magnus",
  "JOHANNESSEN Tobias Halland",
  "TILLER Rasmus",
  "KRON Andreas",
  "WÆRENSKJOLD Søren",
  "HOELGAARD Markus",
  "JANSEN Amund Grøndahl",
  "LEKNESSUND Andreas",
  "ABRAHAMSEN Jonas",
  "DVERSNES Fredrik",
  "BLIKRA Erlend",
  "SKAARSETH Anders",
  "WALLIN Rasmus Bøgh",
  "HOLTER Ådne",
  "KULSET Johannes",
  "RESELL Erik Nordsæter",
  "FREDHEIM Stian",
  "JOHANNESSEN Anders Halland",
  "HVIDEBERG Jonas Iversby",
  "URIANSTAD BUGGE Martin",
  "DALBY Simon",
  "BLUME LEVY William",
  "BÉVORT Carl-Frederik",
  "PEDERSEN Henrik",
  "LØLAND Sakarias Koller",
  "KULSET Magnus",
  "FIORELLI Filippo",
  "ZANONCELLO Enrico",
  "COVILI Luca",
  "MARCELLUSI Martin",
  "MAGLI Filippo",
  "COLNAGHI Luca",
  "TAROZZI Manuele",
  "PINARELLO Alessandro",
  "MARTINELLI Alessio",
  "TOLIO Alex",
  "ROJAS Vicente",
  "CONFORTI Lorenzo",
  "PINAZZI Mattia",
  "SCALCO Matteo",
  "BIAGINI Federico",
  "PALETTI Luca",
  "TURCONI Filippo",
  "CETTOLIN Filippo",
  "CRUZ Edward",
  "FERRARO Santiago",
  "HERREÑO Martin Santiago",
  "MONTAGNER Andrea",
  "STENICO Mattia",
  "VAN AERT Wout",
  "YATES Simon",
  "KELDERMAN Wilco",
  "VINGEGAARD Jonas",
  "BENOOT Tiesj",
  "LAPORTE Christophe",
  "KRUIJSWIJK Steven",
  "VAN BAARLE Dylan",
  "KUSS Sepp",
  "KOOIJ Olav",
  "CAMPENAERTS Victor",
  "JORGENSON Matteo",
  "ZINGLE Axel",
  "VAN DER SANDE Tosh",
  "MCLAY Daniel",
  "VALTER Attila",
  "VERMOTE Julien",
  "AFFINI Edoardo",
  "UIJTDEBROEKS Cian",
  "TULETT Ben",
  "HAGENES Per Strand",
  "LEMMEN Bart",
  "GLOAG Thomas",
  "BEHRENS Niklas",
  "BRENNAN Matthew",
  "GRAAT Tijmen",
  "NORDHAGEN Jørgen",
  "VAN BELLE Loe",
  "HUISING Menno",
  "VLIEGEN Loïc",
  "TIZZA Marco",
  "DE TIER Floris",
  "BARBIER Pierre",
  "VAN ROOY Kenneth",
  "WEEMAES Sasha",
  "REYNDERS Jens",
  "DESAL Ceriel",
  "PERSICO Davide",
  "MEENS Johan",
  "VILLA Giacomo",
  "DE MEESTER Luca",
  "LAMBRECHT Michiel",
  "VERMOOTE Jelle",
  "MATTHYS Louka",
  "BEZZA Quentin",
  "VAN HAUTEGEM Leander",
  "RENARD-HAQUIN Henri-François",
  "PORTSMOUTH Tom",
  "BAGUELIN Jocelyn",
  "PAPON Victor",
  "VAN PETEGEM Axandre",
  "ULISSI Diego",
  "POELS Wout",
  "TEUNISSEN Mike",
  "BETTIOL Alberto",
  "HIGUITA Sergio",
  "MASNADA Fausto",
  "BALLERINI Davide",
  "VELASCO Simone",
  "BOL Cees",
  "CHAMPOUSSIN Clément",
  "FORTUNATO Lorenzo",
  "MULUBRHAN Henok",
  "GATE Aaron",
  "KANTER Max",
  "SCARONI Christian",
  "FEDOROV Yevgeniy",
  "MALUCELLI Matteo",
  "CONCI Nicola",
  "SCHELLING Ide",
  "TEJADA Harold",
  "CHARMIG Anthon",
  "LÓPEZ Harold Martín",
  "KUZMIN Anton",
  "GAZZOLI Michele",
  "ROMELE Alessandro",
  "VINOKUROV Nicolas",
  "TONEATTI Davide",
  "VAN BEKKUM Darren",
  "KAJAMINI Florian Samuel",
  "SU Haoyu"
]
last_names = ["VAN DER POEL","PHILIPSEN","GROVES","HERMANS","VERMEERSCH","BOVEN","DEHAIRS","DEL GROSSO","DILLIER","KIELICH","MEURISSE","PLANCKAERT","PLOWRIGHT","RICKAERT","RIESEBEEK","UHLIG","VAN TRICHT","VERSTRYNGE","BAYER","DEBRUYNE","GAZE","GHYS","GLIVAR","GOGL","HOLLMANN","JANSSENS","PRICE-PEJTERSEN","VAN DEN BOSSCHE","VERGALLITO","MOZZATO","DEMARE","VAUQUELIN","SENECHAL","BIERMANS","CAPIOT","COSTIOU","LE BERRE","VENTURINI","DELAPLACE","EPIS","GARCIA PIERNA","GESBERT","GRONDIN","GUERNALEC","GUERNALEC","GUGLIELMI","HUYS","LOZOUET","RIES","RODRIGUEZ","ROULAND","SCOTSON","SVESTAD-BARDSENG","THIERRY","TJOTTA","VERRE","MOHORIC","BAUHAUS","BILBAO","BUITRAGO","TIBERI","HAIG","MARTINEZ","WRIGHT","ARNDT","CARUSO","GOVEKAR","PASQUALON","STANNARD","TRAEEN","VAN MECHELEN","BRUTTOMESSO","BURATTI","ERMAKOV","ERZEN","EULALIO","GRADEK","KEPPLINGER","MIHOLJEVIC","PAASSCHENS","PICKERING","SKERL","STOCKWELL","TU","VAN DER MEULEN","ZAMBANINI","ALLENO","ALVAREZ","ANGULO","APARICIO","BOUGLAS","BURNETT","CAVIA","CHUMIL","DE LA CALLE","DELGADO","DIAZ","FAGUNDEZ","FAURA","FERNANDEZ","FUENTES","GARCIA PIERNA","JACKSON","KMINEK","KOYAMA","KUDUS","MARTIN","OKAMIKA","SAINBAYAR","BARCELO","LEITAO","ARRIOLA-BENGOA","BABOR","BALDERSTONE","BERWICK","BOU","CASTELLON","DARDER","DIAZ","FERNANDEZ","GONZALEZ","GUARDENO","IBANEZ","JOHNSTON","LOPEZ","MOLENAAR","NICOLAU","OTRUBA","PENUELA","PRADES","SILVA","SORARRAIN","STITES","TEUNS","COQUARD","ARANBURU","ALLEGAERT","ANIOLKOWSKI","BUCHMANN","CARR","FERRON","FRETIN","HERRADA","IZAGIRRE","RENARD","ROBEET","DE GENDT","DEBEAUMARCHE","FINE","IZQUIERDO","KNIGHT","LASTRA","MAAS","MAHOUDO","MAISONOBE","MONIQUET","OLDANI","OURSELIN","PEREZ","SAMITIER","THOMAS","TOUMIRE","TOUZE","COSNEFROY","BENNETT","NAESEN","GALL","GAUTHERAT","GODON","LAFAY","LAPEIRA","PARET-PEINTRE","ARMIRAIL","BISSEGGER","DE BONDT","DE PESTEL","DEWULF","GUDMESTAD","TRONCHON","VENDRAME","BERTHET","BISIAUX","BOUCHARD","CHAMBERLAIN","ISIDORE","LABROSSE","PEDERSEN","PETERS","POLLEFLIET","PRODHOMME","SCOTSON","SEIXAS","STAUNE-MITTET","HEALY","POWLESS","ASGREEN","CARAPAZ","VAN DEN BERG","ALBANESE","MIHKELS","VALGREN","BATTISTELLA","CARTHY","CHAVES","COSTA","DOULL","HONORE","BAUDIN","BELOKI","CEPEDA","MACKELLAR","NERURKAR","QUINN","RAFFERTY","ROOTKIN-GRAY","RYAN","SHAW","STEINHAUSER","SWEENY","TODOME","VAN DER LEE","WALKER","ABERASTURI","DEKKER","AGIRRE","ALUSTIZA","BERASATEGI","BIZKARRA","BONILLO","DE LA PARTE","DINA","GANZABAL","HENNEQUIN","ISASA","JUARISTI","LOPEZ DE ABETXUKO","LOPEZ","MARTIN","MINTEGI","MURGUIALDAY","SUTTON","VAN DER TUUK","ZUBELDIA","CLYNHENS","COLMAN","CRABBE","DE VYLDER","DEJAEGHER","DEMAN","DENS","DEWEIRDT","GEENS","GERITS","HESTERS","LANHOVE","MARIS","VAN HEMELEN","VAN POUCKE","VANDENBRANDEN","VANDENSTORME","VANDEVELDE","VANHOOF","VERCOUILLIE","KUNG","GAUDU","MADOUAS","GREGOIRE","MARTIN","PENHOET","ASKEY","BYSTROM","CAVAGNA","GENIETS","JACOBS","LE GAC","MOLARD","PACHER","BARTHE","BRAZ AFONSO","DAVY","DONNENWIRTH","GERMANI","GRUEL","LE HUITOUZE","PALENI","ROCHAS","ROLLAND","RUSSO","VAN DEN BERG","WALLS","GANNA","EWAN","RODRIGUEZ","SHEFFIELD","TARLING","ARENSMAN","BERNAL","FOSS","KWIATKOWSKI","LAURANCE","THOMAS","TURNER","DE PLUS","HEIDUK","JUNGELS","WATSON","AUGUST","CASTROVIEJO","FRAILE","HAMILTON","LANGELLOTTI","LEONARD","PUCCIO","RIVERA","RODRIGUEZ","SHMIDT","SWIFT","SWIFT","GIRMAY","THIJSSEN","KAMP","MARIT","REX","ARTZ","BONNEU","BRAET","BUSATTO","GOOSSENS","KUYPERS","MEINTJES","PAGE","PETIT","ROTA","RUTSCH","VAN DER HOORN","ZIMMERMANN","BARRE","COLLEONI","DE POOTER","FAURE PROST","PAQUOT","PETILLI","SMITH","VAN BOVEN","VAN HOECKE","VAN SINTMAARTENSDIJK","ACKERMANN","GEE","HOFSTETTER","LUTSENKO","WILLIAMS","BLACKMORE","STRONG","WOODS","BOIVIN","CLARKE","EINHORN","FUGLSANG","HIRT","KOGUT","LOUVEL","NEILANDS","RICCITELLO","SHEEHAN","STEWART","VAN ASBROECK","VERNON","BENNETT","COTE","FRIGO","FROOME","HOULE","PICKRELL","RAISBERG","SCHULTZ","SCHWARZMANN","GROENEWEGEN","MATTHEWS","O'CONNOR","DUNBAR","SCHMID","WALSCHEID","BOUWMAN","DURBRIDGE","ENGELHARDT","HARPER","HATHERLY","KRIJNSEN","MEZGEC","O'BRIEN","PLAPP","ZANA","BERHE","DE MARCHI","DE PRETTO","DONALDSON","DOUBLE","FOLDAGER","GAMPER","HELLEMOSE","HEPBURN","JUUL-JENSEN","REINDERS","STEWART","SUTTERLIN","SOSA","AZANZA","AZNAR","AZNAR","BERRADE","BRUSTENGA","CARRASCOSA","COBO","ELOSEGUI","ETXEBERRIA","FERNANDEZ","GALVAN","GIMENO","GUTIERREZ","IRIBAR","MIQUEL","PARRA","RETEGI","RUIZ","SOTO","URIARTE","WENZEL","PEDERSEN","MILAN","NYS","SKJELMOSE","STUYVEN","CONSONNI","SKUJINS","BAGIOLI","CICCONE","GEOGHEGAN HART","KONRAD","KRAGH ANDERSEN","MOLLEMA","VACEK","DECLERCQ","HOOLE","KAMNA","KIRSCH","LOPEZ","SIMMONS","TEUTENBERG","THEUNS","WITHEN PHILIPSEN","BERNARD","GHEBREIGZABHIER","GIBBONS","MOSCA","OOMEN","VERGAERDE","VERONA","DE LIE","VAN EETVELT","BERCKMOES","MENTEN","SEGAERT","TAMINIAUX","BEULLENS","DE BUYST","DE SCHUYTENEER","GREGAARD","LIVYNS","VAN DE PAAR","VAN MOER","CRAPS","CURRIE","DRIZNERS","GIDDINGS","GRIGNARD","ORINS","SEPULVEDA","SLOCK","THOMPSON","VAN DE WYNKELE","VANDENABEELE","VEISTROFFER","MAS","CASTRILLO","FORMOLO","GARCIA CORTINA","GAVIRIA","AULAR","CEPEDA","GUERREIRO","NORSGAARD","QUINTANA","ROMEO","ROMO","RUBIO","SANCHEZ","SERRANO","TESFATSION","ARCAS","BARRENETXEA","BARTA","CANAL","CIMOLAI","HESSMANN","MILESI","MORO","MUHLBERGER","OLIVEIRA","PEDRERO","PESCADOR","TORRES","ARMITT","BEADLE","BRAND","COLLADON","DAUGE","DE GRAEVE","IRVINE","KOPECKY","LOZANO","MCDONALD","MULLER","PERCRULE","PERON","PERRACCHIONE","PHIPPEN","POLGA","POLI","RIDOLFO","SMITH","WATTELLE","ANDRESEN","JAKOBSEN","BARDET","BARGUIL","BITTNER","DEGENKOLB","ONLEY","POOLE","VAN UDEN","EEKHOFF","FLYNN","LEEMREIZE","ROOSEN","VAN DEN BROEK","VERMAERKE","WELTEN","COMBAUD","DHONDT","DINHAM","EDDY","EDMONDSON","HAMILTON","KOERDT","LEIJNSE","MARKL","MARTINEZ","NABERMAN","VAN DEN BERG","BAIS","BAIS","BUTTIGIEG","CRESCIOLI","DE CASSAN","GARCIA","GOMEZ","LONARDI","MAESTRI","MARTIN","MUNOZ","PENALVER","PIETROBON","PIGANZOLI","RACCAGNI","SERRANO","SEVILLA","TERCERO","TONELLI","ZOCCARATO","PIDCOCK","MOSCHETTI","NIZZOLO","BAX","BRAMBILLA","CHRISTEN","FRISON","LIEPINS","MALECKI","STEIMLE","TOWNSEND","VADER","AZPARREN","AZPARREN","BADILATTI","CALZONI","CAMPRUBI","DE LA CRUZ","DONOVAN","GONZALEZ","HOWSON","PARISINI","PIDCOCK","VANHOUCKE","ZUKOWSKY","VAN GILS","LAZKANO","ROGLIC","HINDLEY","MARTINEZ","MEEUS","PITHIE","TRATNIK","VLASOV","WELSFORD","ADRIA","LIPOWITZ","VAN POPPEL","DENZ","FISHER-BLACK","KOCH","SOBRERO","VAN DIJKE","VAN DIJKE","ALEOTTI","HAJEK","HERZOG","MACIEJUK","MOSCON","MULLEN","PALZER","PELLIZZARI","WANDAHL","ZWIEHOFF","ARASHIRO","BALDACCINI","BALMER","CONTI","DURIC","FORTIN","GONZALEZ","IACCHI","MEO","NENCINI","PIRAS","QUARTUCCI","RAJOVIC","ROLANDO","SAMUDIO","SBARAGLI","STEWART","TISSIERES","TSARENKO","VERRANDO","VIVIANI","EVENEPOEL","MERLIER","MAGNIER","VANSEVENANT","LAMPAERT","LAMPERTI","LANDA","SCHACHMANN","VAN GESTEL","VAN WILDER","CATTANEO","EENKHOORN","HAYTER","LECERF","PARET-PEINTRE","PEDERSEN","VAN LERBERGHE","VANGHELUWE","BASTIAENS","CERNY","GAROFOLI","GELDERS","HUBY","KNOX","RACCAGNI NOVIERO","REINDERINK","SERRY","SVRCEK","VERVAEKE","WARLOP","DUPONT","BAUWENS","BLOUWE","CLAEYS","DE KEYSER","DECOTTIGNIES","GODART","GOEMAN","MARCHAND","MUSEEUW","RIGOLE","SANTY","STEVENS","TEUGELS","VANDENBULCKE","VERWILT","JEANNIERE","TESSON","TURGIS","CRAS","GACHIGNARD","SOUPE","BONIFACE","BONNET","BOULAHOITE","BRUNEL","BURGAUDEAU","DAUPHIN","DELBOVE","DELETTRE","DOUBEY","DUJARDIN","GRELLIER","JEGAT","JOUSSEAUME","LATOUR","LEROUX","MANZIN","MARCEROU","RETAILLEAU","VADIC","VERCHER","HIRSCHI","ALAPHILIPPE","DAINESE","DE KLEIJN","TRENTIN","BRENNER","HALLER","MAYRHOFER","STORER","ZIJLAARD","ERIKSSON","ERIKSSON","FROIDEVAUX","HEMING","KELEMEN","KLUCKERS","KOLZE CHANGIZI","KRIEGER","LIENHARD","MIKUTIS","PLUIMERS","RONDEL","STORK","SUTER","THALMANN","VOISARD","WARBASSE","WEISS","WILKSCH","WIRTGEN","POGACAR","POLITT","WELLENS","NARVAEZ","ALMEIDA","AYUSO","CHRISTEN","DEL TORO","MORGADO","YATES","BJERG","MCNULTY","MOLANO","SIVAKOV","SOLER","VERMEERSCH","VINE","BARONCINI","COVI","Grossschartner","HERREGODTS","MAJKA","OLIVEIRA","TORRES","ARRIETA","JOHANSEN","LAENGEN","NOVAK","OLIVEIRA","BOMBOI","EIKING","JOHANNINK","BLOEM","BUDDING","CARBONI","CHRISTOPHERSEN","DE VRIES","GELEIJN","HUENS","HUYET","INKELAAR","KOPECKY","KUBIS","KYFFIN","LOOCKX","MAIRE","MERIS","MOURIS","NIELSEN","PAIGE","STOCKMAN","STOKBRO","TOUPALIK","VERSCHUREN","KRISTOFF","ABRAHAMSEN","CORT","JOHANNESSEN","KRON","TILLER","WAERENSKJOLD","BLIKRA","FREDHEIM","HOELGAARD","LEKNESSUND","BEVORT","BLUME LEVY","DALBY","DVERSNES","HOLTER","HVIDEBERG","JANSEN","JOHANNESSEN","KULSET","KULSET","LOLAND","PEDERSEN","RESELL","SKAARSETH","URIANSTAD BUGGE","WALLIN","FIORELLI","BIAGINI","CETTOLIN","COLNAGHI","CONFORTI","COVILI","CRUZ","FERRARO","HERRENO","MAGLI","MARCELLUSI","MARTINELLI","MONTAGNER","PALETTI","PINARELLO","PINAZZI","ROJAS","SCALCO","STENICO","TAROZZI","TOLIO","TURCONI","ZANONCELLO","VAN AERT","JORGENSON","BENOOT","KOOIJ","LAPORTE","VINGEGAARD","KUSS","VAN BAARLE","YATES","CAMPENAERTS","KELDERMAN","MCLAY","TULETT","UIJTDEBROEKS","VALTER","ZINGLE","AFFINI","BEHRENS","BRENNAN","HAGENES","KRUIJSWIJK","LEMMEN","NORDHAGEN","VAN DER SANDE","VERMOTE","GLOAG","GRAAT","HUISING","VAN BELLE","BARBIER","REYNDERS","VLIEGEN","WEEMAES","BAGUELIN","BEZZA","DE MEESTER","DE TIER","DESAL","LAMBRECHT","MATTHYS","MEENS","PAPON","PERSICO","PORTSMOUTH","RENARD-HAQUIN","TIZZA","VAN HAUTEGEM","VAN PETEGEM","VAN ROOY","VERMOOTE","VILLA","BETTIOL","BALLERINI","BOL","HIGUITA","KANTER","TEUNISSEN","ULISSI","CHAMPOUSSIN","FEDOROV","GATE","MALUCELLI","MASNADA","POELS","SCARONI","SCHELLING","TEJADA","VELASCO","CHARMIG","CONCI","FORTUNATO","GAZZOLI","KAJAMINI","KUZMIN","LOPEZ","MULUBRHAN","ROMELE","SU","TONEATTI","VAN BEKKUM","VINOKUROV"]

def map_to_full_names(abbreviated_list, full_names):
    mapped_names = []
    for abbreviated in abbreviated_list:
        match = process.extractOne(abbreviated, full_names)
        if match:
            mapped_names.append(match[0])  # match[0] is the full name with highest score
    return mapped_names

# Map abbreviated names to full names
full_name_list = map_to_full_names(last_names, full_names)

# Print each mapped name on a new line
for name in full_name_list:
    print(name)